"""Tests des parseurs de descriptions YouTube (Topic et clip)."""

from unittest.mock import MagicMock

from src.models.track import CreditRole
from src.utils.credits_description import (
    parse_description_clip,
    parse_description_clip_llm,
    parse_description_topic,
)

# ── Description Topic réelle : *Dolce Camara* ────────────────────────────────

DOLCE_CAMARA_TOPIC = """\
Provided to YouTube by Believe SAS

Dolce Camara · Booba · SDM

Dolce Camara

℗ Tallac Records

Producer, Vocalist, Lyricist: Booba
Vocalist, Lyricist: SDM
Producer, Composer: Tysko
Mixing Engineer: Nikola Feve "Nk.F"
Recording Engineer: Antonio Olivera

Auto-generated by YouTube.
"""


class TestParseDescriptionTopic:
    def test_dolce_camara(self):
        credits = parse_description_topic(DOLCE_CAMARA_TOPIC)
        assert credits is not None
        names = {c.name for c in credits}
        assert "Booba" in names
        assert "SDM" in names
        assert "Tysko" in names
        assert 'Nikola Feve "Nk.F"' in names
        assert "Antonio Olivera" in names
        assert "Tallac Records" in names

    def test_dolce_camara_roles(self):
        credits = parse_description_topic(DOLCE_CAMARA_TOPIC)
        roles_by_name = {}
        for c in credits:
            roles_by_name.setdefault(c.name, set()).add(c.role)

        assert CreditRole.PRODUCER in roles_by_name["Booba"]
        assert CreditRole.VOCALS in roles_by_name["Booba"]
        assert CreditRole.LYRICIST in roles_by_name["Booba"]

        assert CreditRole.PRODUCER in roles_by_name["Tysko"]
        assert CreditRole.COMPOSER in roles_by_name["Tysko"]

        assert CreditRole.MIXING_ENGINEER in roles_by_name['Nikola Feve "Nk.F"']
        assert CreditRole.RECORDING_ENGINEER in roles_by_name["Antonio Olivera"]
        assert CreditRole.LABEL in roles_by_name["Tallac Records"]

    def test_source_is_youtube_topic(self):
        credits = parse_description_topic(DOLCE_CAMARA_TOPIC)
        assert all(c.source == "youtube_topic" for c in credits)

    def test_not_a_topic_returns_none(self):
        assert parse_description_topic("Just a regular description\nwith no roles") is None

    def test_empty_returns_none(self):
        assert parse_description_topic("") is None
        assert parse_description_topic(None) is None

    def test_label_without_year(self):
        credits = parse_description_topic("℗ Universal Music\nProducer: John")
        assert credits is not None
        labels = [c for c in credits if c.role is CreditRole.LABEL]
        assert len(labels) == 1
        assert labels[0].name == "Universal Music"


# ── Description clip ─────────────────────────────────────────────────────────


class TestParseDescriptionClip:
    def test_prod_by(self):
        credits = parse_description_clip("Prod by Tysko\nMix : Nk.F")
        names = {c.name: c.role for c in credits}
        assert names["Tysko"] is CreditRole.PRODUCER
        assert names["Nk.F"] is CreditRole.MIXING_ENGINEER

    def test_produit_par(self):
        credits = parse_description_clip("Produit par Tysko & DJ Kore")
        producers = [c for c in credits if c.role is CreditRole.PRODUCER]
        assert len(producers) == 2
        assert {c.name for c in producers} == {"Tysko", "DJ Kore"}

    def test_realise_par_is_video_director(self):
        credits = parse_description_clip("Réalisé par Brice Vdh")
        assert credits[0].role is CreditRole.VIDEO_DIRECTOR

    def test_beat_by(self):
        credits = parse_description_clip("Beat by DJ Premier")
        assert credits[0].role is CreditRole.PRODUCER
        assert credits[0].name == "DJ Premier"

    def test_ecrit_par(self):
        credits = parse_description_clip("Écrit par Booba et SDM")
        writers = [c for c in credits if c.role is CreditRole.WRITER]
        assert {c.name for c in writers} == {"Booba", "SDM"}

    def test_mastering(self):
        credits = parse_description_clip("Masterisé par Robin Music")
        assert credits[0].role is CreditRole.MASTERING_ENGINEER

    def test_source_is_youtube_clip(self):
        credits = parse_description_clip("Prod by Tysko")
        assert all(c.source == "youtube_clip" for c in credits)

    def test_empty(self):
        assert parse_description_clip("") == []
        assert parse_description_clip("Abonnez-vous à la chaîne !") == []

    def test_lyrics_colon(self):
        credits = parse_description_clip("Lyrics: Booba")
        assert credits[0].role is CreditRole.LYRICIST
        assert credits[0].name == "Booba"

    def test_written_by_en(self):
        credits = parse_description_clip("Written by Kanye West & Kid Cudi")
        assert len(credits) == 2
        assert all(c.role is CreditRole.WRITER for c in credits)

    def test_name_cleanup_removes_parentheses(self):
        credits = parse_description_clip("Prod by Tysko (ASCAP)")
        assert credits[0].name == "Tysko"


# ── Repli LLM ────────────────────────────────────────────────────────────────


class TestParseDescriptionClipLLM:
    def test_rejects_hallucinated_names(self):
        extractor = MagicMock()
        extractor.extract.return_value = '{"credits": [{"role": "Producer", "names": ["INVENTÉ"]}]}'
        extractor.clean_json_response.side_effect = lambda x: x
        result = parse_description_clip_llm("Prod by Tysko", extractor)
        assert not any(c.name == "INVENTÉ" for c in result)

    def test_keeps_verbatim_names(self):
        extractor = MagicMock()
        extractor.extract.return_value = '{"credits": [{"role": "Producer", "names": ["Tysko"]}]}'
        extractor.clean_json_response.side_effect = lambda x: x
        result = parse_description_clip_llm("Prod by Tysko", extractor)
        assert len(result) == 1
        assert result[0].name == "Tysko"
        assert result[0].role is CreditRole.PRODUCER

    def test_no_vocab_word_returns_empty(self):
        extractor = MagicMock()
        result = parse_description_clip_llm("Abonnez-vous", extractor)
        assert result == []
        extractor.extract.assert_not_called()

    def test_extractor_error_returns_empty(self):
        extractor = MagicMock()
        extractor.extract.side_effect = RuntimeError("ollama down")
        result = parse_description_clip_llm("Prod by someone", extractor)
        assert result == []


# ── Mesuré sur A2H (2026-09-22) : 16 descriptions, 4 crédits trouvés ─────────

WAXX_AUDIO = """\
Waxx, A2H  - La vie ne vaut rien, extrait de l'album Étincelle disponible ici : https://lnk.to/WaxxEtincelleID

https://www.tiktok.com/@waxxgyver
https://www.instagram.com/waxx/

℗ & © 2024 : VF Musiques - tôt Ou tard / Fanzine Planet
"""

JIDDY_TOPIC = """\
Provided to YouTube by Set&Quipe

Le loyer, la teille (feat. A2H) · Jiddy · A2H

℗ SET&QUIPE / MUSICAST - 2016

Released on: 2016-06-15

Auto-generated by YouTube.
"""


class TestTopicNeLitQueDesCredits:
    def test_une_topic_se_reconnait_au_canal_ou_a_sa_premiere_ligne(self):
        from src.utils.credits_description import est_description_topic

        assert est_description_topic(JIDDY_TOPIC)
        assert est_description_topic("Rôle: X", channel="Jiddy - Topic")
        # Un « audio » posté par le label n'est PAS une Topic.
        assert not est_description_topic(WAXX_AUDIO, channel="Waxx")

    def test_les_liens_et_les_dates_ne_sont_pas_des_credits(self):
        """Avant : 4 « Other » (des URL) et un « Released on » en Other « 2016-06-15 »."""
        credits = parse_description_topic(WAXX_AUDIO)
        assert [(c.name, c.role) for c in credits] == [
            ("VF Musiques - tôt Ou tard / Fanzine Planet", CreditRole.LABEL)
        ]
        credits = parse_description_topic(JIDDY_TOPIC)
        assert [(c.name, c.role) for c in credits] == [("SET&QUIPE / MUSICAST", CreditRole.LABEL)]


class TestClipFormesCourtes:
    def test_prod_nu(self):
        for texte in (
            "Prod A2H",
            "Prod KobéBeats",
            "A2H - Mon époque (Prod Dtweezer)",
            "Prod: Xavier",
        ):
            (c,) = parse_description_clip(texte)
            assert c.role == CreditRole.PRODUCER, texte
        assert parse_description_clip("Prod KobéBeats")[0].name == "KobéBeats"
        assert parse_description_clip("A2H - Mon époque (Prod Dtweezer)")[0].name == "Dtweezer"

    def test_real_abrege(self):
        for texte in (
            "Real: Boilerhum (http://www.boilerhum.com)",
            "Réalisation vidéo : Ledok",
            "Réal. : Ledok",
        ):
            (c,) = parse_description_clip(texte)
            assert c.role == CreditRole.VIDEO_DIRECTOR, texte
        assert parse_description_clip("Real: Boilerhum (http://x)")[0].name == "Boilerhum"

    def test_les_liens_ne_font_pas_de_credit(self):
        assert parse_description_clip("Facebook : https://www.facebook.com/a2h") == []
