"""Service crédits — phase YouTube (Topic/clip).

Vérifie la sélection ``manque`` vs ``tout``, l'ordre des voies (Topic → clip),
le batching, la dédup et l'arrêt.
"""

from src.models import Artist, Track
from src.models.track import Credit, CreditRole, TrackVideo
from src.services import credits
from src.services.runtime import Hooks
from tests.test_services_credits import _rt


def _track(title, videos=None, youtube_url=None, creds=None):
    t = Track(title=title, artist=Artist(name="Booba"))
    t.id = hash(title) % 10000
    t.videos = videos or []
    t.youtube_url = youtube_url
    t.credits = list(creds or [])
    return t


TOPIC_DESC = """\
Provided to YouTube by Believe SAS

Dolce Camara · Booba · SDM

Dolce Camara

℗ Tallac Records

Producer, Vocalist, Lyricist: Booba
Producer, Composer: Tysko
Mixing Engineer: Nikola Feve "Nk.F"

Auto-generated by YouTube.
"""

CLIP_DESC = "Prod by Tysko\nMix : Nk.F"


class _FakeYTMusicAPI:
    def __init__(self, meta):
        self._meta = meta
        self.calls = []

    def fetch_video_meta_batch(self, ids):
        self.calls.append(ids)
        return {vid: self._meta.get(vid, {}) for vid in ids}


def _opts(**kw):
    return credits.OptionsCredits(
        genius=False,
        discogs=False,
        paroles_genius=False,
        paroles_ytm=False,
        sync_lrclib=False,
        sync_ytm=False,
        **kw,
    )


def _clients_yt(meta):
    api = _FakeYTMusicAPI(meta)
    return (
        credits.Clients(
            genius=lambda: None,
            discogs=lambda: None,
            lyrics=lambda o: None,
            ytmusic_meta=lambda: api,
        ),
        api,
    )


class TestPhaseYouTube:
    def test_topic_credits_extracted(self):
        vid = "AgFG6_TGdTY"
        t = _track(
            "Dolce Camara",
            videos=[
                TrackVideo(video_id=vid, kind="audio"),
            ],
        )
        cl, api = _clients_yt({vid: {"description": TOPIC_DESC}})
        bilan = credits.run(_rt(), Artist(name="Booba"), [t], _opts(), Hooks(), cl)

        names = {c.name for c in t.credits if c.source == "youtube_topic"}
        assert "Booba" in names
        assert "Tysko" in names
        assert 'Nikola Feve "Nk.F"' in names
        assert bilan.youtube["topic"] >= 1

    def test_clip_fallback_when_no_topic(self):
        vid = "CLIP123abcd"
        t = _track("DKR", youtube_url=f"https://youtube.com/watch?v={vid}")
        cl, _ = _clients_yt({vid: {"description": CLIP_DESC}})
        bilan = credits.run(_rt(), Artist(name="Booba"), [t], _opts(), Hooks(), cl)

        names = {c.name for c in t.credits if c.source == "youtube_clip"}
        assert "Tysko" in names
        assert bilan.youtube["clip"] >= 1

    def test_skips_tracks_with_producer(self):
        t = _track(
            "92i Veyron",
            creds=[Credit(name="Therapy", role=CreditRole.PRODUCER, source="genius")],
        )
        cl, api = _clients_yt({})
        bilan = credits.run(_rt(), Artist(name="Booba"), [t], _opts(), Hooks(), cl)
        assert bilan.youtube["skipped"] == 1

    def test_tout_mode_includes_all(self):
        vid = "TOPIC_VID_1"
        t = _track(
            "92i Veyron",
            videos=[TrackVideo(video_id=vid, kind="audio")],
            creds=[Credit(name="Therapy", role=CreditRole.PRODUCER, source="genius")],
        )
        cl, api = _clients_yt({vid: {"description": TOPIC_DESC}})
        bilan = credits.run(
            _rt(),
            Artist(name="Booba"),
            [t],
            _opts(tout_youtube=True),
            Hooks(),
            cl,
        )
        assert bilan.youtube["selection"] == 1

    def test_dedup_existing_credits(self):
        vid = "TopicVid1234"
        t = _track(
            "Dolce Camara",
            videos=[TrackVideo(video_id=vid, kind="audio")],
            creds=[Credit(name="Tysko", role=CreditRole.PRODUCER, source="genius")],
        )
        cl, _ = _clients_yt({vid: {"description": TOPIC_DESC}})
        credits.run(_rt(), Artist(name="Booba"), [t], _opts(), Hooks(), cl)

        producer_tykso = [
            c for c in t.credits if c.name == "Tysko" and c.role is CreditRole.PRODUCER
        ]
        assert len(producer_tykso) == 1

    def test_stop_during_youtube(self):
        vid = "TopicVid5678"
        t = _track(
            "Test",
            videos=[TrackVideo(video_id=vid, kind="audio")],
        )
        cl, _ = _clients_yt({vid: {"description": TOPIC_DESC}})
        bilan = credits.run(
            _rt(),
            Artist(name="Booba"),
            [t],
            _opts(),
            Hooks(should_stop=lambda: True),
            cl,
        )
        assert not bilan.complete

    def test_no_video_no_crash(self):
        t = _track("Invisible")
        cl, _ = _clients_yt({})
        bilan = credits.run(_rt(), Artist(name="Booba"), [t], _opts(), Hooks(), cl)
        assert bilan.youtube is not None
        assert bilan.complete
