"""schema initial (reflet legacy user_version 46)

Revision ID: e1_initial_schema
Revises:
Create Date: 2026-07-14 03:01:06.864314

Révision de base de la migration SQLAlchemy (phase E). Elle crée le schéma
COMPLET tel qu'il existe aujourd'hui, autogénéré depuis
`src/persistence/schema.py` (lui-même reflet exact de `db.py`).

Mapping legacy → Alembic :
    PRAGMA user_version = 46  ≡  révision « e1_initial_schema »
Une base déjà passée par l'ancien mécanisme (user_version = 46, colonnes déjà
présentes) sera « stampée » à cette révision par le bootstrap de `db.py` (E1d)
SANS rejouer ce upgrade. Sur une base VIDE, `alembic upgrade head` seul suffit
à reproduire le schéma (équivalence `upgrade head` ≡ `create_all` vérifiée par
tests/test_alembic_baseline.py).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1_initial_schema'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('genius_id', sa.Integer(), nullable=True),
    sa.Column('spotify_id', sa.Text(), nullable=True),
    sa.Column('discogs_id', sa.Integer(), nullable=True),
    sa.Column('spotify_monthly_listeners', sa.Integer(), nullable=True),
    sa.Column('ytm_monthly_listeners', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('ytm_channel_id', sa.Text(), nullable=True),
    sa.Column('kworb_total_streams', sa.Integer(), nullable=True),
    sa.Column('kworb_daily_streams', sa.Integer(), nullable=True),
    sa.Column('kworb_lead_streams', sa.Integer(), nullable=True),
    sa.Column('kworb_feat_streams', sa.Integer(), nullable=True),
    sa.Column('kworb_updated', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sqlite_autoincrement=True
    )
    op.create_table('albums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('spotify_streams', sa.Integer(), nullable=True),
    sa.Column('spotify_daily_streams', sa.Integer(), nullable=True),
    sa.Column('spotify_streams_updated', sa.TIMESTAMP(), nullable=True),
    sa.Column('ytm_streams', sa.Integer(), nullable=True),
    sa.Column('ytm_streams_updated', sa.TIMESTAMP(), nullable=True),
    sa.Column('spotify_album_ids', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title', 'artist_id'),
    sqlite_autoincrement=True
    )
    op.create_table('monthly_listeners_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('spotify_listeners', sa.Integer(), nullable=True),
    sa.Column('ytm_listeners', sa.Integer(), nullable=True),
    sa.Column('total_estimated', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_table('tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('album', sa.Text(), nullable=True),
    sa.Column('track_number', sa.Integer(), nullable=True),
    sa.Column('release_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('genius_id', sa.Integer(), nullable=True),
    sa.Column('spotify_id', sa.Text(), nullable=True),
    sa.Column('discogs_id', sa.Integer(), nullable=True),
    sa.Column('bpm', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('genre', sa.Text(), nullable=True),
    sa.Column('genius_url', sa.Text(), nullable=True),
    sa.Column('spotify_url', sa.Text(), nullable=True),
    sa.Column('youtube_url', sa.Text(), nullable=True),
    sa.Column('is_featuring', sa.Boolean(), server_default=sa.text('0'), nullable=True),
    sa.Column('primary_artist_name', sa.Text(), nullable=True),
    sa.Column('featured_artists', sa.Text(), nullable=True),
    sa.Column('lyrics', sa.Text(), nullable=True),
    sa.Column('has_lyrics', sa.Boolean(), server_default=sa.text('0'), nullable=True),
    sa.Column('lyrics_scraped_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('last_scraped', sa.TIMESTAMP(), nullable=True),
    sa.Column('isrc', sa.Text(), nullable=True),
    sa.Column('bpm_source', sa.Text(), nullable=True),
    sa.Column('bpm_confidence', sa.Integer(), nullable=True),
    sa.Column('key_mode_source', sa.Text(), nullable=True),
    sa.Column('reccobeats_resolution', sa.Text(), nullable=True),
    sa.Column('secondary_role', sa.Text(), nullable=True),
    sa.Column('bpm_alt', sa.Integer(), nullable=True),
    sa.Column('lyrics_source', sa.Text(), nullable=True),
    sa.Column('lyrics_synced', sa.Text(), nullable=True),
    sa.Column('lyrics_synced_source', sa.Text(), nullable=True),
    sa.Column('lyrics_synced_confidence', sa.Integer(), nullable=True),
    sa.Column('relationships', sa.Text(), nullable=True),
    sa.Column('certifications', sa.Text(), nullable=True),
    sa.Column('album_certifications', sa.Text(), nullable=True),
    sa.Column('musical_key', sa.Text(), nullable=True),
    sa.Column('key', sa.Text(), nullable=True),
    sa.Column('mode', sa.Text(), nullable=True),
    sa.Column('time_signature', sa.Text(), nullable=True),
    sa.Column('anecdotes', sa.Text(), nullable=True),
    sa.Column('spotify_page_title', sa.Text(), nullable=True),
    sa.Column('spotify_streams', sa.Integer(), nullable=True),
    sa.Column('spotify_daily_streams', sa.Integer(), nullable=True),
    sa.Column('spotify_streams_updated', sa.TIMESTAMP(), nullable=True),
    sa.Column('ytm_streams', sa.Integer(), nullable=True),
    sa.Column('ytm_streams_updated', sa.TIMESTAMP(), nullable=True),
    sa.Column('youtube_url_source', sa.Text(), nullable=True),
    sa.Column('album_override', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title', 'artist_id'),
    sqlite_autoincrement=True
    )
    op.create_table('credits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('role_detail', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('track_id', 'name', 'role', 'role_detail'),
    sqlite_autoincrement=True
    )
    op.create_table('scraping_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_time', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scraping_errors')
    op.drop_table('credits')
    op.drop_table('tracks')
    op.drop_table('monthly_listeners_history')
    op.drop_table('albums')
    op.drop_table('artists')
    # ### end Alembic commands ###
