"""Parseurs PURS pour extraire des crédits depuis les descriptions YouTube.

Deux familles :
- **Topic** (canal « - Topic ») : structuré par le distributeur,
  ``Rôle, Rôle: Nom`` ligne à ligne.
- **Clip** officiel : description LIBRE, motifs fermés FR/EN.
"""

from __future__ import annotations

import json
import re
from typing import TYPE_CHECKING

from src.models.track import Credit, CreditRole
from src.utils.credit_roles import map_role

if TYPE_CHECKING:
    from src.utils.llm_extractor import LLMExtractor

# ── Topic ────────────────────────────────────────────────────────────────────

_TOPIC_IGNORE = {
    "provided to youtube",
    "auto-generated by youtube.",
    "auto-generated by youtube",
}

#: « ℗ Tallac Records », « ℗ 2016 Label », « ℗ & © 2024 : VF Musiques » —
#: mesuré sur A2H (2026-09-22), la 3ᵉ forme entrait telle quelle en Label.
_LABEL_RE = re.compile(r"^℗\s*(?:&\s*©\s*)?(?:\d{4}\s*:?\s*)?(.+?)(?:\s*[-–]\s*\d{4})?$")

#: Clés « X: Y » d'une Topic qui ne sont PAS des crédits (mesuré : « Released
#: on: 2016-06-15 » entrait en Other « 2016-06-15 »).
_TOPIC_NON_CREDIT_KEYS = {"released on", "provided to youtube by", "auto-generated by youtube"}

#: Une ligne qui porte un lien n'est jamais un crédit (« Facebook :
#: https://… », « https://lnk.to/… » : 4 « Other » écrits sur UN morceau).
_URL_RE = re.compile(r"https?://|www\.|//[a-z0-9.-]+\.[a-z]{2,}", re.IGNORECASE)


def est_description_topic(text: str | None, channel: str | None = None) -> bool:
    """Une description Topic se reconnaît à son canal « … - Topic » ou à sa
    première ligne « Provided to YouTube by … » — pas au genre « audio » de la
    vidéo : un audio posté par le label (Waxx) a une description LIBRE."""
    if channel and channel.strip().lower().endswith("- topic"):
        return True
    return bool(text) and text.lstrip().lower().startswith("provided to youtube")


def parse_description_topic(text: str) -> list[Credit] | None:
    """Parse une description Topic (canal « - Topic »).

    Format attendu (une ligne par crédit) ::

        Rôle, Rôle: Nom
        ℗ 2024 Label

    Rend ``None`` si aucune ligne ``Rôle: Nom`` n'est trouvée (ce n'est
    probablement pas une Topic).
    """
    if not text:
        return None

    credits: list[Credit] = []
    found_role_line = False

    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line:
            continue
        if line.lower() in _TOPIC_IGNORE:
            continue

        m_label = _LABEL_RE.match(line)
        if m_label:
            credits.append(
                Credit(name=m_label.group(1).strip(), role=CreditRole.LABEL, source="youtube_topic")
            )
            found_role_line = True
            continue

        if "·" in line or ":" not in line or _URL_RE.search(line):
            continue

        roles_part, _, name = line.partition(":")
        name = name.strip()
        if not name or roles_part.strip().lower() in _TOPIC_NON_CREDIT_KEYS:
            continue

        role_labels = [r.strip() for r in roles_part.split(",") if r.strip()]
        if not role_labels:
            continue

        found_role_line = True
        for label in role_labels:
            credits.append(Credit(name=name, role=map_role(label), source="youtube_topic"))

    return credits if found_role_line else None


# ── Clip ─────────────────────────────────────────────────────────────────────

_CLIP_PATTERNS: list[tuple[re.Pattern[str], CreditRole]] = [
    (
        re.compile(
            r"(?:Prod(?:uit|\.)?|Produc(?:tion|ed))\s+(?:by\s+|par\s+|:\s*)(.+)", re.IGNORECASE
        ),
        CreditRole.PRODUCER,
    ),
    # « Prod A2H », « (Prod Dtweezer) », « Prod: X » — la forme NUE du rap FR
    # (mesuré sur A2H : 3 producteurs sur 16 descriptions, tous manqués).
    (
        re.compile(r"(?:^|\()Prod\.?\s*:?\s*(?!by\b|par\b)([^)\n]+)", re.IGNORECASE),
        CreditRole.PRODUCER,
    ),
    (re.compile(r"Beat\s+by\s+(.+)", re.IGNORECASE), CreditRole.PRODUCER),
    (
        re.compile(
            r"(?:Réalis(?:é|ation)|Direct(?:ed|ion))\s+(?:par\s+|by\s+|:\s*)(.+)", re.IGNORECASE
        ),
        CreditRole.VIDEO_DIRECTOR,
    ),
    # « Real: Boilerhum », « Réalisation vidéo : Ledok », « Réal. : X »
    (
        re.compile(r"^R[ée]al(?:isation|\.)?(?:\s+vid[ée]o)?\s*:\s*(.+)", re.IGNORECASE),
        CreditRole.VIDEO_DIRECTOR,
    ),
    (
        re.compile(r"Mix(?:é|ing|ed)?\s+(?:par\s+|by\s+|:\s*)(.+)", re.IGNORECASE),
        CreditRole.MIXING_ENGINEER,
    ),
    (
        re.compile(r"Master(?:isé|ing|ed)?\s+(?:par\s+|by\s+|:\s*)(.+)", re.IGNORECASE),
        CreditRole.MASTERING_ENGINEER,
    ),
    (re.compile(r"(?:Écrit|Written)\s+(?:par\s+|by\s+)(.+)", re.IGNORECASE), CreditRole.WRITER),
    (re.compile(r"(?:Lyrics|Paroles)\s*:\s*(.+)", re.IGNORECASE), CreditRole.LYRICIST),
    (
        re.compile(r"Record(?:ed|ing)\s+(?:par\s+|by\s+|:\s*)(.+)", re.IGNORECASE),
        CreditRole.RECORDING_ENGINEER,
    ),
]

_NAME_SPLIT_RE = re.compile(r"\s*[,&x]\s+|\s+(?:et|and|feat\.?)\s+", re.IGNORECASE)
_NAME_CLEAN_RE = re.compile(r"[(\[@#].*$")

_LLM_VOCAB = re.compile(
    r"\b(?:prod|beat|mix|master|réal|written|paroles|écrit|engineer|ingé)\b",
    re.IGNORECASE,
)


def _split_names(raw: str) -> list[str]:
    """Découpe une chaîne de noms séparés par virgule, &, x, et, and."""
    parts = _NAME_SPLIT_RE.split(raw.strip())
    result = []
    for p in parts:
        cleaned = _NAME_CLEAN_RE.sub("", p).strip().rstrip(".")
        if cleaned and len(cleaned) > 1:
            result.append(cleaned)
    return result


def parse_description_clip(text: str) -> list[Credit]:
    """Parse une description de clip officiel avec des motifs fermés FR/EN."""
    if not text:
        return []

    credits: list[Credit] = []
    for line in text.splitlines():
        line = line.strip()
        if not line:
            continue
        for pattern, role in _CLIP_PATTERNS:
            m = pattern.search(line)
            if m:
                for name in _split_names(m.group(1)):
                    credits.append(Credit(name=name, role=role, source="youtube_clip"))
                break
    return credits


# ── Repli LLM pour clip ─────────────────────────────────────────────────────


def parse_description_clip_llm(
    text: str,
    extractor: LLMExtractor,
) -> list[Credit]:
    """Repli LLM pour les descriptions de clip sans match regex.

    Un nom n'est retenu que s'il apparaît VERBATIM dans la description
    (garde anti-hallucination, comme l'ancrage Kworb).
    """
    if not text or not _LLM_VOCAB.search(text):
        return []

    from src.utils.llm_extractor import build_credits_prompt

    prompt = build_credits_prompt(text)
    try:
        raw = extractor.extract(prompt)
    except Exception:  # noqa: BLE001
        return []

    raw_json = extractor.clean_json_response(raw)
    try:
        data = json.loads(raw_json)
    except (json.JSONDecodeError, ValueError):
        return []

    credits: list[Credit] = []
    text_lower = text.lower()
    for entry in data.get("credits", []):
        role_label = entry.get("role", "")
        for name in entry.get("names", []):
            if not name or name.lower() not in text_lower:
                continue
            credits.append(Credit(name=name, role=map_role(role_label), source="youtube_clip"))
    return credits
